config/routes.rb
Rails.application.routes.draw do
  # devise_for :admins
  # devise_for :members
    devise_for :admins, controllers: {
  sessions:      'admins/sessions',
  passwords:     'admins/passwords',
  registrations: 'admins/registrations'
}
    devise_for :members, controllers: {
  sessions:      'members/sessions',
  passwords:     'members/passwords',
  registrations: 'members/registrations'
}
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  


  scope module: :public do

    root to: "homes#top"
    get     "/about" => "homes#about"

    resources :works, only: [:show, :index] do
      resources :reviews
      post "/forums/:id" => "forums#favorite"
      resources :forums do
        resources :comments, only: [:create]
      end
    end

    post "/works/reviews/:id" => "reviews#favorite"
    post "/works/:id/reviews/:id" => "reviews#favorite"
    post "/works/:id" => "works#category_create"

    get     "/mypages/with_tag"           => "mypages#with_tag", as: 'with_tag'
    get     "/mypages/favorite_forum"     => "mypages#favorite_forum", as: 'favorite_forum'
    post    "/mypages/tag"                => "mypages#tag", as: 'tag'
    get     "/members/delete_check"       => "mypages#delete_check", as: 'delete_check'
    patch   "/members/delete"             => "mypages#delete", as: 'delete'
    get     "/members/follow"             => "mypages#follow_index", as: 'follow_index'
    get     "/members/follow_review"      => "mypages#follow_review", as: 'follow_review'

    resources :mypages

    get     "/others/with_tag"           => "others#with_tag", as: 'with_tag_others'
    resources :others

    resources :work_mngs,only: [:index, :destroy, :update]

    resources :actors, only: [:index]
    get     "/actors/:id"           => "actors#actor_works", as: 'actor_works'

    resources :genres, only: [:index]
    get     "/genres/:id"           => "genres#genre_works", as: 'genre_works'
    
    resources :relationships, only: [:create, :destroy]
    
  end

  namespace :admin do
    get "/" => "homes#top"

    resources :works do
      collection do
        get "new_2"
        post "new_2"
        get "new_2_1"
        post "new_2_1"
        get "new_3"
        post "new_3"
        get "new_3_1"
        post "new_3_1"
        get 'new_confirm'
        post 'new_confirm'

        get "edit_2"
        post "edit_2"
        get "edit_2_1"
        post "edit_2_1"
        get "edit_3"
        post "edit_3"
        get "edit_3_1"
        post "edit_3_1"
        get 'edit_confirm'
        post 'edit_confirm'

        delete "actors/:id" => "work#destroy"
      end
      resources :reviews,only: [:index,:destroy]
      resources :forums,only: [:index,:show,:destroy]
    end

    resources :genres,only: [:index, :create, :destroy]
    resources :actors,only: [:index, :create, :destroy]
    resources :members,only: [:index, :show, :edit, :update, :destroy]
  end

end

app/models/work.rb
class Work < ApplicationRecord
  attr_accessor :image_cache
  mount_uploader :image, ImageUploader

  has_many :genre_mngs, dependent: :destroy
  has_many :actor_mngs, dependent: :destroy
  has_many :reviews, dependent: :destroy
  has_many :work_mngs, dependent: :destroy
  has_many :forums, dependent: :destroy

  enum medium: {
    "アニメ": 0,
    "映画": 1,
    "ドラマ": 2,
    "漫画": 3,
    "小説": 4
  }

end

app/controllers/admin/works_controller.rb
class Admin::WorksController < ApplicationController
  before_action :authenticate_admin!
  before_action :work_set_q, only: [:index]
  before_action :actor_set_q, only: [:new_2,:new_2_1,:edit_2,:edit_2_1]
  before_action :genre_set_q, only: [:new_3,:new_3_1,:edit_3,:edit_3_1]

  def index
    @works_all = Work.all.pluck(:id)

    @anime = "アニメ"
    @movie = "映画"
    @drama = "ドラマ"
    @comic = "漫画"
    @novel = "小説"
    @all = "総合"

    @works = []

    if params[:g] == "アニメ"
      @works_all.each do |work|
        if Work.find(work).medium == "アニメ"
          @works.push(work)
        end
      end
    elsif params[:g] == "映画"
      @works_all.each do |work|
        if Work.find(work).medium == "映画"
          @works.push(work)
        end
      end
    elsif params[:g] == "ドラマ"
      @works_all.each do |work|
        if Work.find(work).medium == "ドラマ"
          @works.push(work)
        end
      end
    elsif params[:g] == "漫画"
      @works_all.each do |work|
        if Work.find(work).medium == "漫画"
          @works.push(work)
        end
      end
    elsif params[:g] == "小説"
      @works_all.each do |work|
        if Work.find(work).medium == "小説"
          @works.push(work)
        end
      end
    else
      @works = @works_all
    end
  end

  def show
    @work = Work.find(params[:id])
    @genres = @work.genre_mngs.pluck(:genre_id)

    if @work.medium != "小説" or @work.medium != "漫画"
      @actors = @work.actor_mngs.pluck(:actor_id)
    end

    @reviews_all = Review.where(work_id: @work.id)
    @reviews =  Review.where(work_id: @work.id).order('updated_at DESC').limit(5)

    if @reviews != []
      scores = @reviews_all
      @score_avg = scores.sum { |i| i[:score]} / Review.where(work_id: @work.id).count
    else
      @score_avg = 0
    end
  end

  def new
   @work = Work.new
  end

  def new_2
   # 次のステップで表示するformに必要な情報を用意
    @work = Work.new(work_params)
    @actors = Actor.all
    @actors = Actor.page(params[:page])
    @checked_actors = []

   #入力漏れ防止
   if work_params[:title].blank? or
      work_params[:medium].blank? or
      work_params[:source].blank? or
      work_params[:author].blank? or
      work_params["release_date(1i)"].blank? or
      work_params["release_date(2i)"].blank? or
      work_params["release_date(3i)"].blank? or
      work_params[:synopsis].blank? or
      @work.image.url.blank? or
      @work.image.cache_name.blank?

     flash[:notice] ="必要項目を全て入力してください"
     redirect_to new_admin_work_path
   end

    # form からの情報をセッションに一時保存
    session[:title] = work_params[:title]
    session[:medium] = work_params[:medium]
    session[:source] = work_params[:source]
    session[:author] = work_params[:author]
    session[:release_date_1i] = work_params["release_date(1i)"]
    session[:release_date_2i] = work_params["release_date(2i)"]
    session[:release_date_3i] = work_params["release_date(3i)"]
    session[:synopsis] = work_params[:synopsis]
    session[:image_url] = @work.image.url
    session[:image_cache_name] = @work.image.cache_name

    if session[:medium]  == "漫画" or session[:medium] == "小説"
      redirect_to new_3_admin_works_path
    end
  end

  def new_2_1
    # 登録した出演者の情報をsessionに保存する
    if session[:actors] == nil
      session[:actors] = []
    end

    if work_params[:is_deleted_all] == "true"
      session.delete(:actors)

    elsif work_params[:is_deleted].blank? == false
      session[:actors].delete(work_params[:is_deleted])

    elsif params[:q].blank? or params[:q][:is_search] != "true"
      # 出演者がすでに登録済みの場合は弾く
      if session[:actors].include?(work_params[:actor]) == false
       session[:actors].push(work_params[:actor])
      end

    end

    # 次のステップで表示するformに必要な情報を用意
    @work = Work.new
    @actors = Actor.all
    @actors = Actor.page(params[:page])
    @checked_actors = session[:actors]

    # もう一度同じviewをレンダリングする
    render "new_2"

  end

  def new_3
   # 出演者の入力漏れ防止
   if session[:actors].blank?
    flash[:notice] ="出演者を入力してください"
    # 次のステップで表示するformに必要な情報を用意
    @work = Work.new
    @actors = Actor.all
    @actors = Actor.page(params[:page])
    @checked_actors = session[:actors]
    render "new_2"
   end
   
    # 次のステップで表示するformに必要な情報を用意
    @work = Work.new
    @genres = Genre.all
    @genres = Genre.page(params[:page])
    @checked_genres = []
    
  end

  def new_3_1
    # 登録したジャンルの情報をsessionに保存する
    if session[:genres] == nil
      session[:genres] = []
    end

    if work_params[:is_deleted_all] == "true"
      session.delete(:genres)

    elsif work_params[:is_deleted].blank? == false
      session[:genres].delete(work_params[:is_deleted])

    elsif params[:q].blank? or params[:q][:is_search] != "true"
      # ジャンルがすでに登録済みの場合は弾く
      if session[:genres].include?(work_params[:genre]) == false
       session[:genres].push(work_params[:genre])
      end

    end

    # 次のステップで表示するformに必要な情報を用意
    @work = Work.new
    @genres = Genre.all
    @genres = Genre.page(params[:page])
    @checked_genres = session[:genres]

    # もう一度同じviewをレンダリングする
    render "new_3"

  end

  def new_confirm
   # ジャンルの入力漏れ防止
   if session[:genres].blank?
    flash[:notice] ="ジャンルを入力してください"
    redirect_to new_3_admin_works_path
   end
   
    @work = Work.new(
     title: session[:title],
     medium: session[:medium],
     source: session[:source],
     author: session[:author],
     release_date: Date.parse(session[:release_date_1i]+"-"+session[:release_date_2i]+"-"+session[:release_date_3i]),
     synopsis: session[:synopsis],
     )

    @image_url = session[:image_url]
    @image_cache_name = session[:image_cache_name]

    @actors = session[:actors]
    @genres = session[:genres]

  end

  def create
    @work = Work.new(work_params)
    @work.image.retrieve_from_cache! params[:cache][:image]

    if @work.save
     if @work.medium != "漫画" and @work.medium != "小説"
      # 作品と出演者の中間テーブルの作成
      session[:actors].each do|actor|
       @actor_mng = ActorMng.new(
         work_id: @work.id,
         actor_id: actor
        )
       @actor_mng.save
      end
     end

       # 作品とジャンルの中間テーブルの作成
      session[:genres].each do|genre|
       @genre_mng = GenreMng.new(
         work_id: @work.id,
         genre_id: genre
        )
       @genre_mng.save
      end

      # sessin を全て空にする
      session.delete(:title)
      session.delete(:medium)
      session.delete(:source)
      session.delete(:author)
      session.delete(:release_date)
      session.delete(:synopsis)
      session.delete(:image_url)
      session.delete(:image_cache_name)
      session.delete(:actors)
      session.delete(:genres)

      redirect_to admin_work_path(@work.id)
    else
      render new_admin_work_path
    end

  end

  def edit
    @before_work = Work.find(params[:id])
    session[:id] = params[:id]
    @work = Work.new
  end

  def edit_2
    #入力漏れ防止
    if work_params[:title].blank? or
       work_params[:medium].blank? or
       work_params[:source].blank? or
       work_params[:author].blank? or
       work_params["release_date(1i)"].blank? or
       work_params["release_date(2i)"].blank? or
       work_params["release_date(3i)"].blank? or
       work_params[:synopsis].blank?

      flash[:notice] ="必要項目を全て入力してください"
      redirect_to new_admin_work_path
    end

    @actors = Actor.all
    @actors = Actor.page(params[:page])
    @checked_actors = Work.find(session[:id]).actor_mngs.pluck(:actor_id)
    session[:actors] = @checked_actors.map(&:to_s)

    # 次のステップで表示するformに必要な情報を用意
    @work = Work.new(work_params)

    # form からの情報をセッションに一時保存
    session[:title] = work_params[:title]
    session[:medium] = work_params[:medium]
    session[:source] = work_params[:source]
    session[:author] = work_params[:author]
    session[:release_date_1i] = work_params["release_date(1i)"]
    session[:release_date_2i] = work_params["release_date(2i)"]
    session[:release_date_3i] = work_params["release_date(3i)"]
    session[:synopsis] = work_params[:synopsis]
    session[:image_url] = @work.image.url
    session[:image_cache_name] = @work.image.cache_name

    if session[:medium]  == "漫画" or session[:medium] == "小説"
      redirect_to edit_3_admin_works_path
    end

  end

  def edit_2_1
     # 登録した出演者の情報をsessionに保存する
    if session[:actors] == nil
      session[:actors] = []
    end

    if work_params[:is_deleted_all] == "true"
      session.delete(:actors)

    elsif work_params[:is_deleted].blank? == false
      session[:actors].delete(work_params[:is_deleted])

    elsif params[:q].blank? or params[:q][:is_search] != "true"
      # 出演者がすでに登録済みの場合は弾く
      if session[:actors].include?(work_params[:actor]) == false
       session[:actors].push(work_params[:actor])
      end

    end

    # 次のステップで表示するformに必要な情報を用意
    @work = Work.new
    @actors = Actor.all
    @actors = Actor.page(params[:page])
    @checked_actors = session[:actors]

    # もう一度同じviewをレンダリングする
    render "edit_2"

  end

  def edit_3
    # 次のステップで表示するformに必要な情報を用意
    @before_work = Work.find(session[:id])
    @work = Work.new
    @genres = Genre.all
    @genres = Genre.page(params[:page])
    @checked_genres = @before_work.genre_mngs.pluck(:genre_id)
    session[:genres] = @checked_genres.map(&:to_s)
  end

  def edit_3_1
    # 登録したジャンルの情報をsessionに保存する
    if session[:genres] == nil
      session[:genres] = []
    end

    if work_params[:is_deleted_all] == "true"
      session.delete(:genres)

    elsif work_params[:is_deleted].blank? == false
      session[:genres].delete(work_params[:is_deleted])

    elsif params[:q].blank? or params[:q][:is_search] != "true"
      # ジャンルがすでに登録済みの場合は弾く
      if session[:genres].include?(work_params[:genre]) == false
       session[:genres].push(work_params[:genre])
      end

    end

    # 次のステップで表示するformに必要な情報を用意
    @work = Work.new
    @genres = Genre.all
    @genres = Genre.page(params[:page])
    @checked_genres = session[:genres]

    # もう一度同じviewをレンダリングする
    render "edit_3"
  end

  def edit_confirm
    @before_work = Work.find(session[:id])

app/helpers/admin/works_helper.rb
module Admin::WorksHelper
end

app/views/admin/works/edit.html.erb
<div class="row" style="padding-bottom: 10px;">
  <div class = "col-md-5">
    <div class="sub-ti">
      <h3>作品編集（1/3）</h>
    </div>
  </div>
</div>

<%= form_with model: @work,url:  {action: 'edit_2'},local: true do |f| %>
  <div class="row" style="padding-bottom: 10px;">
    <div class = "col-md-10 offset-md-2">

      <table class="normal-table">
        <tr>
          <th><%= f.label :作品名 %></th>
          <td><%= f.text_field :title,:size=>"60", :placeholder => "作品名", autofocus: true ,value:@before_work.title%></td>
        </tr>

        <tr>
          <th><%= f.label :作品媒体 %></th>
          <td><%= f.select(:medium,[["アニメ"],["映画"],["ドラマ"],["漫画"],["小説"]], { include_blank: '選択してください',selected:@before_work.medium})%></td>
        </tr>

        <tr>
          <th><%= f.label :作品画像 %></th>
          <td>
            <%= f.file_field :image ,value:@work.image %>
            <p>※変更しない場合は入力不要</p>
          </td>
        </tr>

        <tr>
          <th><%= f.label :画像出典元 %></th>
          <td><%= f.text_field :source,:size=>"60" ,value:@before_work.source %></td>
        </tr>

        <tr>
          <th><%= f.label :原作者 %></th>
          <td><%= f.text_field :author,:size=>"60" ,value:@before_work.author%></td>
        </tr>

        <tr>
          <th><%= f.label :公開日 %></th>
          <td>
            <%= f.date_select(
                :release_date,
                use_month_numbers: true,
                start_year:     1990,
                end_year:       (Time.now.year),
                default:        Date.new(Time.now.year),
                date_separator: '/',
                selected: @before_work.release_date
            )%>
          </td>
        </tr>

        <tr>
          <th><%= f.label :あらすじ %></th>
          <td><%= f.text_area :synopsis,size: "60x5"  ,value:@before_work.synopsis%></td>
        </tr>
      </table>

    </div>
  </div>

  <div class="centers">
    <%= f.submit('次に進む',class: 'btn btn-primary') %>
  </div>

<% end %>

app/views/admin/works/edit_3.html.erb
<div class="row">
  <div class="col-md-5">
    <div class="sub-ti">
      <h3>作品編集（3/3）</h3>
    </div>
  </div>
</div>

<br>

<!--検索機能-->
<div class="row">
  <div class="col-md-3">
    <table>
      <%= search_form_for @q, url:  {action: 'edit_3_1'} do |f| %>

          <%= hidden_field_tag "work[is_search]", true %>

        <div class="field">
          <tr>
            <th>
              <%= f.label :name_cont, 'ジャンル検索' %>
            </th>
          </tr>

          <tr>
            <td>
              <%= f.search_field :name_cont, :placeholder => "ジャンル名"%>
              <%= f.hidden_field :is_search, :value => true %>
            </td>
          </tr>

          <tr>
            <td>
              <div class="text-right">
                <div class="actions">
                  <%= f.submit('検索',class: 'btn btn-secondary') %>
                </div>
              </div>
            </td>
          </tr>
        </div>
      <% end %>
    </table>
    <br>
<!--登録したジャンル表示-->
      <div class="field">
        <table class="normal-table">
         <tr>
          <th>登録済ジャンル</th>
         </tr>

         <% if @checked_genres != nil %>
          <% @checked_genres.each do |genre| %>
          <tr>
           <td>
            <%= Genre.find(genre).name %>
           </td>
           <td>
            <%= form_with model: @work,url:  {action: 'edit_3_1'},local: true do |f| %>
             <%= f.hidden_field :is_deleted, :value => genre %>
             <%= f.submit('削除',class: 'btn btn-danger') %>
            <%end%>
           </td>
          </tr>
         <% end %>
        <% end %>
        </table>
        <br>
        <div class="centers">
          <%= form_with model: @work,url:  {action: 'edit_3_1'},local: true do |f| %>
            <%= f.hidden_field :is_deleted_all, :value => true %>
            <%= f.submit('全て削除',class: 'btn btn-danger') %>
          <%end%>
        </div>
      </div>
      <br>
      <div class="centers">
        <%= link_to "次に進む", edit_confirm_admin_works_path, class: 'btn btn-primary' %>
      </div>

  </div> <!-- col end-->

<% if @results.blank? %>
<!--ジャンルを一覧表示-->
  <div class="col-md-9">
    <div class="row">
      <!--1列目-->
      <div class="col-md-5 offset-md-1">
        <table class="list_table">

          <tr>
            <th>ジャンル名</th>
            <th></th>
          </tr>

          <% @genres.each.with_index do|genre,index| %>
            <%if index % 2 == 0%>
              <tr>
                <td>
                  <%=genre.name%>
                </td>

                <td>
                  <div class="centers">
                   <div class="list_table_btn">
                    <%= form_with model: @work,url:  {action: 'edit_3_1'},local: true do |f| %>
                      <%= f.hidden_field :genre, :value => genre.id %>
                      <%= f.submit('登録',class: 'btn btn-success') %>
                    <%end%>
                   </div>
                  </div>
                </td>
              </tr>
            <%end%>
          <%end%>
        </table>
      </div>
      <!--2列目-->
      <div class="col-md-5 offset-md-1">
        <table class="list_table">
          <tr>
            <th>ジャンル名</th>
            <th></th>
          </tr>

          <% @genres.each.with_index do|genre, index| %>
            <%if index % 2 == 1%>
              <tr>
                <td>
                  <%= genre.name %>
                </td>

                <td>
                  <div class="centers">
                   <div class="list_table_btn">
                    <%= form_with model: @work,url:  {action: 'edit_3_1'},local: true do |f| %>
                      <%= f.hidden_field :genre, :value => genre.id %>
                      <%= f.submit('登録',class: 'btn btn-success') %>
                    <%end%>
                   </div>
                  </div>
                </td>
              </tr>
            <%end%>
          <%end%>
        </table>
      </div>
    </div>
  </div>
 <div class="col-md-3 offset-md-6">
   <%= paginate @genres %>
 </div>
</div> <!--row end-->

<% else %>
<!--検索結果を一覧表示-->

  <div class="col-md-9">
    <div class="row">
      <!--1列目-->
      <div class="col-md-5 offset-md-1">
        <table class="list_table">

          <tr>
            <th>ジャンル名</th>
            <th></th>
          </tr>

          <% @results.each.with_index do|genre,index| %>
            <%if index % 2 == 0%>
              <tr>
                <td>
                  <%=genre.name%>
                </td>

                <td>
                  <div class="centers">
                   <div class="list_table_btn">
                    <%= form_with model: @work,url:  {action: 'edit_3_1'},local: true do |f| %>
                      <%= f.hidden_field :genre, :value => genre.id %>
                      <%= f.submit('登録',class: 'btn btn-success') %>
                    <%end%>
                   </div>
                  </div>
                </td>
              </tr>
            <%end%>
          <%end%>
        </table>
      </div>
      <!--2列目-->
      <div class="col-md-5 offset-md-1">
        <table class="list_table">
          <tr>
            <th>ジャンル名</th>
            <th></th>
          </tr>

          <% @results.each.with_index do|genre, index| %>
            <%if index % 2 == 1%>
              <tr>
                <td>
                  <%= genre.name %>
                </td>

                <td>
                  <div class="centers">
                   <div class="list_table_btn">
                    <%= form_with model: @work,url:  {action: 'edit_3_1'},local: true do |f| %>
                      <%= f.hidden_field :genre, :value => genre.id %>
                      <%= f.submit('登録',class: 'btn btn-success') %>
                    <%end%>
                   </div>
                  </div>
                </td>
              </tr>
            <%end%>
          <%end%>
        </table>
      </div>
    </div>
  </div>
</div> <!--row end-->

<br>

<div class="col-md-3 offset-md-6">
 <%= paginate @genres %>
</div>

<% end %>

app/views/admin/works/edit_confirm.html.erb
<div class="row">
  <div class="col-md-5">
    <div class="sub-ti">
      <h3>作品編集確認</h3>
    </div>
  </div>
</div>

<%= form_for @work, url: admin_work_path(@before_work.id),method: :patch do |f| %>

  <div class="row">
   <div class = "col-md-10 offset-md-2">
    <br>
    <table class = "vertical-table">
       <tr>
        <th>タイトル</th>
        <td><%= @work.title%></td>
        <%= f.hidden_field :title %>
       </tr>

       <tr>
       <th>作品画像</th>
       <td>
         <% if @image_url %>
           <%= image_tag(@image_url) %>
           <%= hidden_field_tag :"cache[image]", @image_cache_name %>
         <% else %>
           <%= image_tag @before_work.image.to_s %>
         <% end %>
       </td>
       </tr>

       <tr>
        <th>画像出典元</th>
        <td><%= @work.source %></td>
        <%= f.hidden_field :source %>
       </tr>

       <tr>
        <th>作品媒体</th>
        <td><%= @work.medium %></td>
        <%= f.hidden_field :medium %>
       </tr>

       <tr>
        <th>原作者</th>
        <td><%= @work.author %></td>
        <%= f.hidden_field :author %>
       </tr>

       <tr>
        <th>公開日</th>
        <td><%= @work.release_date %></td>
        <%= f.hidden_field :release_date %>
       </tr>

       <tr>
        <th>あらすじ</th>
        <td><%= @work.synopsis %></td>
        <%= f.hidden_field :synopsis %>
       </tr>
       
       <% if @work.medium != "漫画" and @work.medium != "小説" %>
       <tr>
        <th>出演者</th>
        <td>
          <% @actors.each do |actor| %>
           <%= Actor.find(actor).name %>　<!--左に全角スペースあり-->
          <% end %>
        </td>
       </tr>
       <% end %>

       <tr>
        <th>ジャンル</th>
        <td>
          <% @genres.each do |genre| %>
           <%= Genre.find(genre).name %>　<!--左に全角スペースあり-->
          <% end %>
        </td>
       </tr>
    </table>
   </div>
  </div>

  <div class="centers" style="padding-bottom: 30px;">
    <%= link_to "作り直す", edit_admin_work_path(@before_work.id), class: 'btn btn-secondary' %>
  </div>


  <div class="centers">
    <%= f.submit '編集完了',class: 'btn btn-primary' %>
  </div>

<% end %>

app/views/admin/works/show.html.erb
<div class="row" style="padding-bottom: 30px;">
 <div class = "col-md-5">
  <div class="sub-ti">
   <h2>作品詳細</h2>
  </div>
 </div>
</div>

<div class="row" style="padding-bottom: 10px;">
   <div class = "col-md-5">
     <%= image_tag @work.image.to_s %>
     <p><%= @work.source %></p>
   </div>

   <div class = "col-md-6 offset-md-1">
     <div class="centers" style = "padding-bottom:10px;">
       <h2><%= @work.title %></h2>
       <p><%= @work.medium %></p>
      </div>

     <table class="vertical-table">

       <tr>
         <th>5段階評価</th>
         <td><%= @score_avg %></td>
       </tr>

       <tr>
         <th>公開日</th>
         <td><%= @work.release_date %></td>
       </tr>

       <tr>
         <th>ジャンル</th>
         <td>
           <% @genres.each do|genre| %>
            <%= Genre.find(genre).name %>　<!--左に全角スペースあり-->
           <% end %>
         </td>
       </tr>

       <tr>
         <th>原作者</th>
         <td><%= @work.author %></td>
       </tr>

       <% if @work.medium != "漫画" and @work.medium != "小説" %>
       <tr>
         <th>出演者</th>
         <td>
           <% @actors.each do|actor| %>
            <%= Actor.find(actor).name %>　<!--左に全角スペースあり-->
           <% end %>
         </td>
       </tr>
       <% end %>

     </table>
  </div>
</div>

<br>

<div class="row" style="padding-bottom: 10px;">
 <div class = "col-md-10 offset-md-1">
  <table class="vertical-table">
    <tr>
      <th>あらすじ</th>
      <td><%= @work.synopsis%></td>
    </tr>
  </table>
 </div>
</div>

<div class="row" style="padding-bottom:30px;">
 <div class = "col-md-3 offset-md-9">
   <%= link_to("/admin/works/#{@work.id}/edit") do %>
    <button type="button" class="btn btn-success">編集する</button>
   <%end%>
 </div>
</div>

<div class="row" style="padding-bottom:30px;">
 <div class = "col-md-3 offset-md-9">
   <%= link_to "スレッド一覧を見る", admin_work_forums_path(@work.id) %>
 </div>
</div>

<div class="row" style="padding-bottom:30px;">
 <div class = "col-md-5">
   <h2>レビュー</h2>
 </div>
</div>

<div class="row" style="padding-bottom:30px;">
 <div class = "col-md-12">

   <div class="row" style="padding-top :10px;">
     <div class = "col-md-12">
       <table class="table">
         <tr>
           <th>投稿日</th>
           <th>評価</th>
           <th>投稿者</th>
           <th>レビュー</th>
           <th></th>
         </tr>

         <% @reviews.each do|review| %>
          <tr>
           <td width="160">
            <%= review.created_at.to_s(:datetime_jp) %>
           </td>

           <td width="100">
            <%= review.score %>
           </td>

           <td width="160">
            <%= Member.find(review.member_id).name %>
           </td>

           <td width="650">
            <b><%= review.title %></b>
            <br>
            <%= review.sentence %>
           </td>

           <td width="300">
            <%= link_to(admin_work_review_path(@work.id,review.id),method: :delete, data: {confirm: "本当に削除しますか？"} ) do %>
              <button type="button" class="btn btn-danger">削除</button>
            <% end %>
            </td>

          </tr>
         <% end %>

       </table>

     </div>
   </div>

 </div>
</div>

<div class="row" style="padding-bottom:30px;">
 <div class = "col-md-2 offset-md-10">
   <%= link_to "レビューをすべて見る", admin_work_reviews_path(@work.id) %>
 </div>
</div>