config/routes.rb
Rails.application.routes.draw do
  # devise_for :admins
  # devise_for :members
    devise_for :admins, controllers: {
  sessions:      'admins/sessions',
  passwords:     'admins/passwords',
  registrations: 'admins/registrations'
}
    devise_for :members, controllers: {
  sessions:      'members/sessions',
  passwords:     'members/passwords',
  registrations: 'members/registrations'
}
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  


  scope module: :public do

    root to: "homes#top"
    get     "/about" => "homes#about"

    resources :works, only: [:show, :index] do
      resources :reviews
      post "/forums/:id" => "forums#favorite"
      resources :forums do
        resources :comments, only: [:create]
      end
    end

    post "/works/reviews/:id" => "reviews#favorite"
    post "/works/:id/reviews/:id" => "reviews#favorite"
    post "/works/:id" => "works#category_create"

    get     "/mypages/with_tag"           => "mypages#with_tag", as: 'with_tag'
    get     "/mypages/favorite_forum"     => "mypages#favorite_forum", as: 'favorite_forum'
    post    "/mypages/tag"                => "mypages#tag", as: 'tag'
    get     "/members/delete_check"       => "mypages#delete_check", as: 'delete_check'
    patch   "/members/delete"             => "mypages#delete", as: 'delete'
    get     "/members/follow"             => "mypages#follow_index", as: 'follow_index'
    get     "/members/follow_review"      => "mypages#follow_review", as: 'follow_review'

    resources :mypages

    get     "/others/with_tag"           => "others#with_tag", as: 'with_tag_others'
    resources :others

    resources :work_mngs,only: [:index, :destroy, :update]

    resources :actors, only: [:index]
    get     "/actors/:id"           => "actors#actor_works", as: 'actor_works'

    resources :genres, only: [:index]
    get     "/genres/:id"           => "genres#genre_works", as: 'genre_works'
    
    resources :relationships, only: [:create, :destroy]
    
  end

  namespace :admin do
    get "/" => "homes#top"

    resources :works do
      collection do
        get "new_2"
        post "new_2"
        get "new_2_1"
        post "new_2_1"
        get "new_3"
        post "new_3"
        get "new_3_1"
        post "new_3_1"
        get 'new_confirm'
        post 'new_confirm'

        get "edit_2"
        post "edit_2"
        get "edit_2_1"
        post "edit_2_1"
        get "edit_3"
        post "edit_3"
        get "edit_3_1"
        post "edit_3_1"
        get 'edit_confirm'
        post 'edit_confirm'

        delete "actors/:id" => "work#destroy"
      end
      resources :reviews,only: [:index,:destroy]
      resources :forums,only: [:index,:show,:destroy]
    end

    resources :genres,only: [:index, :create, :destroy]
    resources :actors,only: [:index, :create, :destroy]
    resources :members,only: [:index, :show, :edit, :update, :destroy]
  end

end

app/models/actor.rb
class Actor < ApplicationRecord
  
  has_many :actor_mngs, dependent: :destroy
  
end

app/models/actor_mng.rb
class ActorMng < ApplicationRecord

  belongs_to :work
  belongs_to :actor

end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  
  belongs_to :forum
  belongs_to :member
  
end

app/models/forum.rb
class Forum < ApplicationRecord

  has_many :comments, dependent: :destroy
  has_many :forum_mngs, dependent: :destroy

  belongs_to :work
  belongs_to :member

end

app/models/forum_mng.rb
class ForumMng < ApplicationRecord

  belongs_to :forum
  belongs_to :member
  
end

app/models/genre.rb
class Genre < ApplicationRecord
  
  has_many :genre_mngs, dependent: :destroy
  
end

app/models/genre_mng.rb
class GenreMng < ApplicationRecord
  
  belongs_to :work
  belongs_to :genre
  
end

app/models/member.rb
class Member < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :work_mngs, dependent: :destroy
  has_many :forums, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :forum_mngs, dependent: :destroy
  has_many :reviews, dependent: :destroy
  has_many :review_mngs, dependent: :destroy

  # フォロー機能
  has_many :active_follows, class_name: "Follow", foreign_key: :following_id, dependent: :destroy
  has_many :passive_follows, class_name: "Follow", foreign_key: :follower_id, dependent: :destroy

  has_many :relationships
  has_many :followings, through: :relationships, source: :follow
  has_many :reverse_of_relationships, class_name: 'Relationship', foreign_key: 'follow_id'
  has_many :followers, through: :reverse_of_relationships, source: :member

  def follow(other_member)
    unless self == other_member
      self.relationships.find_or_create_by(follow_id: other_member.id)
    end
  end

  def unfollow(other_member)
    relationship = self.relationships.find_by(follow_id: other_member.id)
    relationship.destroy if relationship
  end

  def following?(other_member)
    self.followings.include?(other_member)
  end

end

app/models/relationship.rb
class Relationship < ApplicationRecord
  
  belongs_to :member
  belongs_to :follow, class_name: "Member"

  validates :member_id, presence: true
  validates :follow_id, presence: true
  
end

app/models/review.rb
class Review < ApplicationRecord

  belongs_to :member
  belongs_to :work

  has_many :review_mngs, dependent: :destroy

end

app/models/review_mng.rb
class ReviewMng < ApplicationRecord
  
  belongs_to :review
  belongs_to :member
  
end

app/models/work.rb
class Work < ApplicationRecord
  attr_accessor :image_cache
  mount_uploader :image, ImageUploader

  has_many :genre_mngs, dependent: :destroy
  has_many :actor_mngs, dependent: :destroy
  has_many :reviews, dependent: :destroy
  has_many :work_mngs, dependent: :destroy
  has_many :forums, dependent: :destroy

  enum medium: {
    "アニメ": 0,
    "映画": 1,
    "ドラマ": 2,
    "漫画": 3,
    "小説": 4
  }

end

app/models/work_mng.rb
class WorkMng < ApplicationRecord

  belongs_to :work
  belongs_to :member

  enum category: {
    "お気に入り": 0,
    "後で見る": 1,
    "断念": 2,
    "閲覧済み": 3,
  }

end

app/controllers/admin/forums_controller.rb
class Admin::ForumsController < ApplicationController
  before_action :authenticate_admin!
  before_action :forum_set_q, only: [:index]
  
  def index
    @work = Work.find(params[:work_id])
    if @work.forums != []
      @forums = @work.forums.page(params[:page])
    else
      @forums = []
    end
  end

  def show
    @work = Work.find(params[:work_id])
    @coment = Comment.new
    @forum = Forum.find(params[:id])
    @creater = Member.find(@forum.member_id).name
    @comments = Comment.where(forum_id: params[:id]).page(params[:page])
  end
  
  def destroy
    @forum = Forum.find(params[:id])
    @forum.destroy
    redirect_to admin_work_forums_path(params[:work_id])
  end
  
        private

  def forum_set_q
    @q = Forum.ransack(params[:q])
    @results = []
    if params[:q]
      @results = @q.result
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys:
    [:name,:opinion])
  end

  def after_sign_in_path_for(resource)
    case resource
    when Admin
      admin_works_path
    when Member
      root_path
    end
  end

end

app/helpers/admin/actors_helper.rb
module Admin::ActorsHelper
end

app/helpers/admin/forums_helper.rb
module Admin::ForumsHelper
end

app/helpers/admin/homes_helper.rb
module Admin::HomesHelper
end

app/helpers/admin/works_helper.rb
module Admin::WorksHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/relationships_helper.rb
module RelationshipsHelper
end

app/views/admin/forums/index.html.erb
<div class="row" style="padding-bottom: 30px;">
 <div class = "col-md-12">
  <div class="sub-ti">
   <h2><%= @work.title %>のスレッド一覧(管理者用)</h2>
  </div>
 </div>
</div>


<div class="row">
 <div class = "col-md-2 offset-md-9">

  <table>
      <%= search_form_for @q, url: admin_work_forums_path(@work.id) do |f| %>
        <div class="field">
          <tr>
            <th>
              <%= f.label :title_cont, 'スレッド検索' %>
            </th>
          </tr>

          <tr>
            <td>
              <%= f.search_field :title_cont, :placeholder => "スレッド名"%>
            </td>

            <td>
             <div class="actions">
              <%= f.submit('検索',class: 'btn btn-secondary') %>
             </div>
            </td>
          </tr>

        </div>
      <% end %>
    </table>

 </div>
</div>

<div class="row" style="padding-top :10px;">
 <div class = "col-md-12">
    <% if @results.blank? %>
    <!--全てのスレッドを一覧表示-->
     <table class="table">

       <tr>
         <th>作成日</th>
         <th>更新日</th>
         <th>スレッド名</th>
         <th>コメント数</th>
       </tr>

       <% @forums.each do|forum| %>
        <tr>
         <td width="160">
           <%= forum.created_at.to_s(:datetime_jp) %>
         </td>
         
         <td width="160">
           <% if !forum.comments.blank? %>
             <% @comment_new = Comment.where(forum_id: forum.id).order(created_at: :desc).limit(1) %>
             <%= @comment_new.first.created_at.to_s(:datetime_jp) %>
           <% else %>
             <%= forum.created_at.to_s(:datetime_jp) %>
           <% end %>
         </td>
         
         <td width="650">
          <%= link_to "#{forum.title}","/admin/works/#{@work.id}/forums/#{forum.id}" %>
         </td>
         
         <td>
          <%= forum.comments.count %>
         </td>
        </tr>
       <% end %>

     </table>

    <% else %>

    <!--検索結果を一覧表示-->
      <table class="table">

        <tr>
          <th>作成日</th>
          <th>更新日</th>
          <th>スレッド名</th>
          <th>コメント数</th>
        </tr>

      <% @results.each do|forum| %>
        <tr>
          <td width="160"><%= forum.created_at.to_s(:datetime_jp) %></td>
          <td width="80">
           <% if !forum.comments.blank? %>
             <% @comment_new = Comment.where(forum_id: forum.id).order(created_at: :desc).limit(1) %>
             <%= @comment_new.created_at.to_s(:datetime_jp) %>
           <% else %>
             <%= forum.created_at.to_s(:datetime_jp) %>
           <% end %>
         </td>
          <td  width="650"><%= link_to "#{forum.title}","/works/#{@work.id}/forums/#{forum.id}" %></td>
          <td><%= forum.comments.count %></td>
        </tr>
      <% end %>

      </table>

    <% end %>

     <% if @work.forums != [] %>
      <%= paginate @forums %>
     <% end %>

   </div>
</div>

app/views/admin/forums/show.html.erb
<div class="row" style="padding-bottom: 30px;">
 <div class = "col-md-12">
  <div class="sub-ti">
   <h2><%= @forum.title %>(管理者用)</h2>
  </div>
 </div>
</div>

<div class="row" style="padding-bottom:20px">
 <div class = "col-md-12">
   <p>作成者：<%= @creater%></p>
   <p><%= @forum.summary %></p>
 </div>
</div>

<div class="row">
  <div class = "col-md-2 offset-md-6">
    <%= link_to(admin_work_forum_path(@work.id),method: :delete, data: {confirm: "本当に削除しますか？"} ) do %>
      <button type="button" class="btn btn-danger">削除する</button>
    <%end%>
  </div>
</div>

<div class="row">
 <div class = "col-md-2 offset-md-10">
   <p><%= link_to "スレッド一覧に戻る", admin_work_forums_path(@work.id)%></p>
 </div>
</div>

<div class="row">
 <div class = "col-md-12">
    <table class="table">
       <tr>
         <th>投稿日</th>
         <th>本文</th>
       </tr>
       <% @comments.each do|comment| %>
       <tr>
        <td width="100">
         <%= comment.created_at.to_s(:datetime_jp) %>
        </td>

        <td width="500">
         <p>投稿者：<%= Member.find(comment.member_id).name %></p>
         <p><%= comment.opinion %></p>
        </td>
       </tr>
   <% end %>
    </table>

 </div>
</div>