config/routes.rb
Rails.application.routes.draw do
  # devise_for :admins
  # devise_for :members
    devise_for :admins, controllers: {
  sessions:      'admins/sessions',
  passwords:     'admins/passwords',
  registrations: 'admins/registrations'
}
    devise_for :members, controllers: {
  sessions:      'members/sessions',
  passwords:     'members/passwords',
  registrations: 'members/registrations'
}
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  


  scope module: :public do

    root to: "homes#top"
    get     "/about" => "homes#about"

    resources :works, only: [:show, :index] do
      resources :reviews
      post "/forums/:id" => "forums#favorite"
      resources :forums do
        resources :comments, only: [:create]
      end
    end

    post "/works/reviews/:id" => "reviews#favorite"
    post "/works/:id/reviews/:id" => "reviews#favorite"
    post "/works/:id" => "works#category_create"

    get     "/mypages/with_tag"           => "mypages#with_tag", as: 'with_tag'
    get     "/mypages/favorite_forum"     => "mypages#favorite_forum", as: 'favorite_forum'
    post    "/mypages/tag"                => "mypages#tag", as: 'tag'
    get     "/members/delete_check"       => "mypages#delete_check", as: 'delete_check'
    patch   "/members/delete"             => "mypages#delete", as: 'delete'
    get     "/members/follow"             => "mypages#follow_index", as: 'follow_index'
    get     "/members/follow_review"      => "mypages#follow_review", as: 'follow_review'

    resources :mypages

    get     "/others/with_tag"           => "others#with_tag", as: 'with_tag_others'
    resources :others

    resources :work_mngs,only: [:index, :destroy, :update]

    resources :actors, only: [:index]
    get     "/actors/:id"           => "actors#actor_works", as: 'actor_works'

    resources :genres, only: [:index]
    get     "/genres/:id"           => "genres#genre_works", as: 'genre_works'
    
    resources :relationships, only: [:create, :destroy]
    
  end

  namespace :admin do
    get "/" => "homes#top"

    resources :works do
      collection do
        get "new_2"
        post "new_2"
        get "new_2_1"
        post "new_2_1"
        get "new_3"
        post "new_3"
        get "new_3_1"
        post "new_3_1"
        get 'new_confirm'
        post 'new_confirm'

        get "edit_2"
        post "edit_2"
        get "edit_2_1"
        post "edit_2_1"
        get "edit_3"
        post "edit_3"
        get "edit_3_1"
        post "edit_3_1"
        get 'edit_confirm'
        post 'edit_confirm'

        delete "actors/:id" => "work#destroy"
      end
      resources :reviews,only: [:index,:destroy]
      resources :forums,only: [:index,:show,:destroy]
    end

    resources :genres,only: [:index, :create, :destroy]
    resources :actors,only: [:index, :create, :destroy]
    resources :members,only: [:index, :show, :edit, :update, :destroy]
  end

end

app/models/actor.rb
class Actor < ApplicationRecord
  
  has_many :actor_mngs, dependent: :destroy
  
end

app/models/actor_mng.rb
class ActorMng < ApplicationRecord

  belongs_to :work
  belongs_to :actor

end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  
  belongs_to :forum
  belongs_to :member
  
end

app/models/forum.rb
class Forum < ApplicationRecord

  has_many :comments, dependent: :destroy
  has_many :forum_mngs, dependent: :destroy

  belongs_to :work
  belongs_to :member

end

app/models/forum_mng.rb
class ForumMng < ApplicationRecord

  belongs_to :forum
  belongs_to :member
  
end

app/models/genre.rb
class Genre < ApplicationRecord
  
  has_many :genre_mngs, dependent: :destroy
  
end

app/models/genre_mng.rb
class GenreMng < ApplicationRecord
  
  belongs_to :work
  belongs_to :genre
  
end

app/models/member.rb
class Member < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :work_mngs, dependent: :destroy
  has_many :forums, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :forum_mngs, dependent: :destroy
  has_many :reviews, dependent: :destroy
  has_many :review_mngs, dependent: :destroy

  # フォロー機能
  has_many :active_follows, class_name: "Follow", foreign_key: :following_id, dependent: :destroy
  has_many :passive_follows, class_name: "Follow", foreign_key: :follower_id, dependent: :destroy

  has_many :relationships
  has_many :followings, through: :relationships, source: :follow
  has_many :reverse_of_relationships, class_name: 'Relationship', foreign_key: 'follow_id'
  has_many :followers, through: :reverse_of_relationships, source: :member

  def follow(other_member)
    unless self == other_member
      self.relationships.find_or_create_by(follow_id: other_member.id)
    end
  end

  def unfollow(other_member)
    relationship = self.relationships.find_by(follow_id: other_member.id)
    relationship.destroy if relationship
  end

  def following?(other_member)
    self.followings.include?(other_member)
  end

end

app/models/relationship.rb
class Relationship < ApplicationRecord
  
  belongs_to :member
  belongs_to :follow, class_name: "Member"

  validates :member_id, presence: true
  validates :follow_id, presence: true
  
end

app/models/review.rb
class Review < ApplicationRecord

  belongs_to :member
  belongs_to :work

  has_many :review_mngs, dependent: :destroy

end

app/models/review_mng.rb
class ReviewMng < ApplicationRecord
  
  belongs_to :review
  belongs_to :member
  
end

app/models/work.rb
class Work < ApplicationRecord
  attr_accessor :image_cache
  mount_uploader :image, ImageUploader

  has_many :genre_mngs, dependent: :destroy
  has_many :actor_mngs, dependent: :destroy
  has_many :reviews, dependent: :destroy
  has_many :work_mngs, dependent: :destroy
  has_many :forums, dependent: :destroy

  enum medium: {
    "アニメ": 0,
    "映画": 1,
    "ドラマ": 2,
    "漫画": 3,
    "小説": 4
  }

end

app/models/work_mng.rb
class WorkMng < ApplicationRecord

  belongs_to :work
  belongs_to :member

  enum category: {
    "お気に入り": 0,
    "後で見る": 1,
    "断念": 2,
    "閲覧済み": 3,
  }

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys:
    [:name,:opinion])
  end

  def after_sign_in_path_for(resource)
    case resource
    when Admin
      admin_works_path
    when Member
      root_path
    end
  end

end

app/helpers/admin/homes_helper.rb
module Admin::HomesHelper
end

app/helpers/admin/works_helper.rb
module Admin::WorksHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/relationships_helper.rb
module RelationshipsHelper
end

app/views/admins/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/admins/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Matomemo</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

 <body>
  <header>

   <nav class="navbar navbar-expand-sm  mt-3 mb-3">
    
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav4" aria-controls="navbarNav4" aria-expanded="false" aria-label="Toggle navigation">
       <span class="navbar-toggler-icon"></span>
      </button>
      
     <%= link_to "/", method: :get do %>
       <i class="navbar-brand"></i><%= image_tag 'logo.png',:size => '150x80'%>
     <% end %>
     
      <div class="collapse navbar-collapse justify-content-end">
      <ul class="navbar-nav">
        <% if admin_signed_in? %>
    
           <li class="nav-work">
            <%= link_to "作品一覧", admin_works_path, method: :get %>
           </li>
    
           <li class="nav-work">
            <%= link_to "ジャンル一覧", admin_genres_path, method: :get %>
           </li>
    
           <li class="nav-work">
            <%= link_to "出演者一覧", admin_actors_path, method: :get %>
           </li>
    
           <li class="nav-work">
            <%= link_to "会員一覧", admin_members_path, method: :get %>
           </li>
    
           <li class="nav-work">
            <%= link_to "ログアウト", destroy_admin_session_path, method: :delete %>
           </li>
    
         <% elsif member_signed_in?  %>
           <p>ようこそ、<%=current_member.name%>さん！</p>
    
            <li class="nav-work">
              <%= link_to "マイページ", mypages_path %>
            </li>
    
            <li class="nav-work">
              <%= link_to "作品一覧", works_path %>
            </li>
            
            <li class="nav-work">
              <%= link_to "出演者一覧", actors_path %>
            </li>
            
            <li class="nav-work">
              <%= link_to "ジャンル一覧", genres_path %>
            </li>
    
    
            <li class="nav-work">
              <%= link_to "ログアウト", destroy_member_session_path, method: :delete %>
            </li>
    
          <% else %>
    
            <li class="nav-work">
             <%= link_to "/about", method: :get do %>
              About
             <% end %>
            </li>
    
            <li class="nav-work">
             <%= link_to "/members/sign_up", method: :get do %>
             新規登録
             <% end %>
            </li>
    
            <li class="nav-work">
             <%= link_to "/members/sign_in", method: :get do %>
             ログイン
             <% end %>
             </li>
          <% end %>
         </ul>
       </div>
   </nav>
  </header>

  <% if flash[:notice] %>
    <%= flash[:notice] %>
  <% end %>

 <div class="container">
     <%= yield %>
 </div>

 </body>
</html>